version: "3"
services:
  app:
    container_name: xit_app
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - mongo
  mongo:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    volumes:
      - ./volume_data:/data/db
